language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y freeglut3

install:
    - python -m pip install cython
    - python -m pip install numpy

script:
    - python setup.py check
    - python setup.py build_ext --inplace --force
    - python setup.py test
